In [7]:
import pandas as pd

In [9]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [13]:
pip install pandas sqlalchemy pymysql openpyxl

Requirement already satisfied: pandas in C:\Users\kolli\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.0.3)
Requirement already satisfied: sqlalchemy in C:\Users\kolli\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.0.50)
Requirement already satisfied: pymysql in C:\Users\kolli\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.2.0)
Requirement already satisfied: openpyxl in C:\Users\kolli\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\kolli\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\kolli\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\kolli\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: greenlet>=1 in C:\Users\kolli\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\kolli\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: et-xmlfile in C:\Users\kolli\AppData\Local\Programs\Python\Python313\Lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in C:\Users\kolli\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [28]:
df = pd.read_excel("Sales_raw.xlsx")

In [11]:
df.head()

   Order_ID Order_Date Customer Region  Product  Sales   Cost
0      1001 2023-01-13    Rohit  South   Mobile  23289  19118
1      1002 2023-10-07     Aman   West   Laptop   8905   5593
2      1003 2023-11-05    Rahul  South  Monitor  59987  39959
3      1004 2024-02-19    Rahul  South  Printer  49597  33892
4      1005 2024-01-26   Anjali  North   Laptop  54797  34468

In [14]:
df.tail()

     Order_ID Order_Date Customer Region  Product  Sales   Cost
515      1389 2024-02-12    Vikas  North   Laptop  17924  12145
516      1496 2023-04-24    Kiran  North  Printer  23434  16388
517      1031 2023-02-19    Vikas   East  Printer  58883  43579
518      1317 2023-07-05     Aman  North   Laptop  76781  66865
519      1409 2024-01-16    Pooja  North  Monitor  19969  13586

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    520 non-null    int64
 1   Order_Date  502 non-null    datetime64[us]
 2   Customer    520 non-null    str
 3   Region      520 non-null    str
 4   Product     520 non-null    str
 5   Sales       520 non-null    int64
 6   Cost        520 non-null    int64
dtypes: datetime64[us](1), int64(3), str(3)
memory usage: 28.6 KB

In [16]:
df.describe()

          Order_ID                  Order_Date         Sales          Cost
count   520.000000                         502    520.000000    520.000000
mean   1250.867308  2023-08-18 09:36:34.422310  41129.607692  30675.001923
min    1001.000000         2023-01-04 00:00:00   5205.000000   3272.000000
25%    1124.750000         2023-05-03 00:00:00  22015.750000  16388.000000
50%    1251.500000         2023-08-15 00:00:00  41044.000000  30349.000000
75%    1377.250000         2023-12-12 00:00:00  59245.000000  43363.500000
max    1500.000000         2024-03-26 00:00:00  79928.000000  71417.000000
std     145.030140                         NaN  21605.117122  16598.086873

In [17]:
df.describe(include='all')

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost
count,520.000000,502,520,520,520,520.000000,520.000000
unique,NaN,NaN,10,4,5,NaN,NaN
top,NaN,NaN,Suresh,South,Printer,NaN,NaN
freq,NaN,NaN,58,136,109,NaN,NaN
mean,1250.867308,2023-08-18 09:36:34.422310,NaN,NaN,NaN,41129.607692,30675.001923
min,1001.000000,2023-01-04 00:00:00,NaN,NaN,NaN,5205.000000,3272.000000
25%,1124.750000,2023-05-03 00:00:00,NaN,NaN,NaN,22015.750000,16388.000000
50%,1251.500000,2023-08-15 00:00:00,NaN,NaN,NaN,41044.000000,30349.000000
75%,1377.250000,2023-12-12 00:00:00,NaN,NaN,NaN,59245.000000,43363.500000
max,1500.000000,2024-03-26 00:00:00,NaN,NaN,NaN,79928.000000,71417.000000
std,145.030140,NaN,NaN,NaN,NaN,21605.117122,16598.086873

In [18]:
df.shape

(520, 7)

In [19]:
df.size

3640

In [29]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer', 'Region', 'Product', 'Sales',
       'Cost'],
      dtype='str')

In [30]:
df.columns = df.columns.str.lower()

In [31]:
df.columns

Index(['order_id', 'order_date', 'customer', 'region', 'product', 'sales',
       'cost'],
      dtype='str')

In [34]:
df.duplicated().any()

np.True_

In [35]:
df.duplicated().sum()

np.int64(20)

In [41]:
df = df.drop_duplicates()

In [42]:
df

     order_id order_date customer region  product  sales   cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
495      1496 2023-04-24    Kiran  North  Printer  23434  16388
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970
497      1498 2023-05-08     Aman   East   Tablet  19160  15636
498      1499        NaT    Pooja   West   Mobile  59266  44326
499      1500 2023-10-07    Vikas  North  Printer  34567  22426

[500 rows x 7 columns]

In [43]:
df.duplicated().sum()

np.int64(0)

In [44]:
df.isnull().sum()

order_id       0
order_date    18
customer       0
region         0
product        0
sales          0
cost           0
dtype: int64

In [48]:
df['order_date'] = pd.to_datetime(df['order_date'],errors = 'coerce')

In [54]:
df = df.dropna(subset='order_date')
df

     order_id order_date customer region  product  sales   cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
494      1495 2023-10-18    Rahul  South  Monitor  46709  40931
495      1496 2023-04-24    Kiran  North  Printer  23434  16388
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970
497      1498 2023-05-08     Aman   East   Tablet  19160  15636
499      1500 2023-10-07    Vikas  North  Printer  34567  22426

[482 rows x 7 columns]

In [53]:
df.isnull().sum()

order_id      0
order_date    0
customer      0
region        0
product       0
sales         0
cost          0
dtype: int64

In [55]:
df['profit'] = df['sales']-df['cost']

In [56]:
df['year'] = df['order_date'].dt.year
df['month'] = df['order_date'].dt.month

In [57]:
df

,order_id,order_date,customer,region,product,sales,cost,profit,year,month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,2023,1
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,3312,2023,10
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,20028,2023,11
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,2024,1
...,...,...,...,...,...,...,...,...,...,...
494,1495,2023-10-18,Rahul,South,Monitor,46709,40931,5778,2023,10
495,1496,2023-04-24,Kiran,North,Printer,23434,16388,7046,2023,4
496,1497,2023-06-27,Anjali,South,Laptop,49007,35970,13037,2023,6
497,1498,2023-05-08,Aman,East,Tablet,19160,15636,3524,2023,5
499,1500,2023-10-07,Vikas,North,Printer,34567,22426,12141,2023,10

In [62]:
df.to_csv('Sales_cleaned.csv', index=False)

In [65]:
from sqlalchemy import create_engine

In [67]:
df = pd.read_csv('Sales_cleaned.csv')

In [68]:
df

,order_id,order_date,customer,region,product,sales,cost,profit,year,month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,2023,1
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,3312,2023,10
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,20028,2023,11
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,2024,1
...,...,...,...,...,...,...,...,...,...,...
477,1495,2023-10-18,Rahul,South,Monitor,46709,40931,5778,2023,10
478,1496,2023-04-24,Kiran,North,Printer,23434,16388,7046,2023,4
479,1497,2023-06-27,Anjali,South,Laptop,49007,35970,13037,2023,6
480,1498,2023-05-08,Aman,East,Tablet,19160,15636,3524,2023,5
481,1500,2023-10-07,Vikas,North,Printer,34567,22426,12141,2023,10

In [69]:
engine = create_engine('mysql+pymysql://root:Manasa%4024@localhost:3306/salesdb')

In [70]:
df.to_sql(name ='sales_data', con = engine, if_exists='replace',index = False)

482